version: '3.7'

services:
    database:
        image: mysql:5.7
        container_name: mysql_container
        restart: always
        volumes:
            - db-volume:/var/lib/mysql
            - ./articles.sql:/docker-entrypoint-initdb.d/articles.sql
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: 

    app:
        image: diagnosis
        container_name: diagnosis_api
        restart: always
        volumes:
            - ./diagnosis:/var/www/html
        ports:
            - "8080:8080"
        depends_on:
            - database

    view:
        image: diagnosisView
        container_name: diagnosis_view
        restart: always
        volumes:
            - ./diagnosis:/var/www/html
        ports:
            - 8082:82
        depends_on:
            - app

volumes:
    db-volume: